### ISSUE TITLE
Usability improvements prototyping

### ISSUE THREAD

**Issue by tuomasnironen** [vaadin/vaadin-date-picker#100]
Prototype and ask user feedback (lightweight UX testing) would the following changes improve the date picker usability:
- [ ] tweak mouse scroll speed to less sensitive ([issue origin](https://docs.google.com/document/d/1bnp7bMDPEVh0CWg37cjyK52o__Npzg0iAMFwcjBY-3E/edit#bookmark=id.w2oytfomdqjy)) (#102)
- [x] replace year scroll dots with month names ([issue origin](https://docs.google.com/document/d/1bnp7bMDPEVh0CWg37cjyK52o__Npzg0iAMFwcjBY-3E/edit#bookmark=id.syn362g2g59n)) (#138)
  - At the same time, consider adding another breakpoint above 375px and increase the width and font-size of the year scroller
- [x] stack year numbers stacked more closely vertically ([issue origin](https://docs.google.com/document/d/1bnp7bMDPEVh0CWg37cjyK52o__Npzg0iAMFwcjBY-3E/edit#bookmark=id.syn362g2g59n)) (#138)
- [ ] ~~ARIA spec regarding year browse with keyboard shortcut (prototype if needed, [issue origin](https://docs.google.com/document/d/1bnp7bMDPEVh0CWg37cjyK52o__Npzg0iAMFwcjBY-3E/edit#bookmark=id.i2nkbrstx8kq))~~ (Shift+Page Up/Down already work)
- [ ] replace month grid with e.g. big year number overlay while scrolling (scrolling speed distracting eyesight, [issue origin](https://docs.google.com/document/d/1bnp7bMDPEVh0CWg37cjyK52o__Npzg0iAMFwcjBY-3E/edit#bookmark=id.orexbyaafnj3))

**Comment by manolo** [comment]
@jouni shouldn't we close these old issues because of inactivity also the context of the component has changed a lot since it was prototyped. We can open new feature tickets when we need them anyways.

**Comment by jouni** [comment]
Well, I suppose we can close them. I suppose all the important issues will resurface eventually, so there’s no point in keeping these open to “not forget”.
