### ISSUE TITLE
Feature backlog

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-date-picker#30]
### 1.0
- [x] Replace `iron-list` with `vaadin-scroller` #33 
- [x] Refactor dropdown alignment/position, with a responsive breakpoint #34 
  - Validate our layout design with mobile devices
- [x] Year navigation #35 
- [x] Localization #36 

---
- [x] Today shortcut #40 
- [x] Setting the initial position of month view (without setting the value) #46
- [x] Integration with `iron-form` #51
- [x] Themability #55
- [x] Keyboard navigation #76

---
### Future
- [x] Min/max date #197
- [x] Keyboard input and related input validation #196 #238 
- [x] Week numbers
- [x] Accessibility, screenreader support (ARIA) #70
- [ ] Disabled dates #646
- [ ] Range selection #2 
- [ ] Selecting multiple dates
- [ ] Selecting repeating dates (weekly/monthly/yearly)
- [ ] Allow customizing the date cells
- [ ] Inline date picker
- [ ] Adding custom content to the dropdown (custom footer, etc)
