### ISSUE TITLE
Flow API related todo list

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-date-picker#457]
### Value compatibility

Make sure all public-available user input elements follow these rules:

- [ ] the `value` property is declared as `String`
- [ ] the `value` property is not read-only and allows changes
- [ ] the `value` property declaration has `notify: true`

### Validation compatibility

Make sure all public-available validatable elements follow these rules:

- [ ] the `invalid` property is declared as `Boolean`
- [ ] the `invalid` property has `notify: true`
- [ ] `validate()` method updates the `invalid` state property

### `vaadin-date-picker-mixin.html`

- [ ] ❓ deprecate `open()` and `close()` methods for future removal in next major version, since duplicate of writable `opened` property
- [ ] ❓ deprecate `cancel()` method for future removal
  - probably duplicate of `comboBox.opened = false; comboBox.value = initialValue;`
- [ ] in `validate()` and `checkValidity()` methods, document the `value` argument and mark as deprecated to be removed in next major
- [ ] mark with `@private` and deprecate the `hasValue` property, only the argument should be kept for styling

### Mark with `@private` for the element classes

- `vaadin-date-picker-overlay.html`:
  - [ ] `class DatePickerOverlayElement`
- `vaadin-infinite-scroller.html`:
  - [ ] `class InfiniteScrollerElement`
- `vaadin-month-calendar.html`:
  - [ ] `class MonthCalendarElement`
